Best friend rooms
agicitag/BondageClubTools pull request #32
Opened 2022-09-24 07:16 UTC by crimsontropy

2022-09-24 12:43 UTC, agicitag commented on extension/bct.js
> +				Player.BCT.bctSettings.bestFriendsRoomShare = false;
This would cause the user to have to redo their setting when they enabled `bestFriendsEnabled` again.

2022-09-24 12:49 UTC, agicitag commented on extension/bct.js
> +								if (sender.BCT?.bctSettings?.bestFriendsEnabled === true) AddRelationDialog(sender);
Doesnt get removed again when the setting is being disabled while already in a chatroom together.

2022-09-24 12:52 UTC, agicitag commented on extension/bct.js
> +	// TODO: best friend list to Set instead of Array?
Please do general todos as an issue and not in the code. Only do code todos if they are referring to that specific code at that point.

2022-09-24 13:12 UTC, agicitag commented on extension/bct.js
> +	w.ChatRoomCanAddAsBF = () => {
`w.` not needed here. Also remove line 22, as its not necessary without this.

2022-09-24 13:15 UTC, agicitag commented on extension/bct.js
> +		var bctOnlineCheck = false;
`let` instead of `var`.

2022-09-24 13:19 UTC, agicitag commented on extension/bct.js
> +		BCT_BEEP_Ack_FRIEND_MSG = "AckFriends",
`ACK` instead of `Ack`.

2022-09-24 13:22 UTC, agicitag commented on extension/bct.js
> +	bctBestFriend();
Call it at the bulk of function calls beginning in line 50.

2022-09-24 13:24 UTC, agicitag requested changes
Changes requested in comments.

2022-09-24 14:06 UTC, crimsontropy commented on extension/bct.js
> +				Player.BCT.bctSettings.bestFriendsRoomShare = false;
Removed this and added the checks on if statements instead where `bestFriendsRoomShare` is called.

2022-09-24 14:08 UTC, crimsontropy commented on extension/bct.js
> +								if (sender.BCT?.bctSettings?.bestFriendsEnabled === true) AddRelationDialog(sender);
Fixed

2022-09-24 14:09 UTC, crimsontropy commented on extension/bct.js
> +	// TODO: best friend list to Set instead of Array?
Got it. Removed.

2022-09-24 14:09 UTC, crimsontropy commented on extension/bct.js
> +	w.ChatRoomCanAddAsBF = () => {
Fixed

2022-09-24 14:09 UTC, crimsontropy commented on extension/bct.js
> +		var bctOnlineCheck = false;
Done.

2022-09-24 14:09 UTC, crimsontropy commented on extension/bct.js
> +		BCT_BEEP_Ack_FRIEND_MSG = "AckFriends",
Done.

2022-09-24 14:10 UTC, crimsontropy commented on extension/bct.js
> +	bctBestFriend();
Done.

2022-09-24 15:01 UTC, agicitag approved these changes

2022-09-25 17:56 UTC, agicitag approved these changes

2022-09-25 17:57 UTC, merged